### ISSUE TITLE
Tweetar publicações do Diário Oficial

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/diario-de-feira#1]
Para cada nova publicação do diário um tweet deve ser criado.

TODO

- [x] Conectar na API do Twitter (#6)
- [x] Buscar edição do diário na API da Maria Quitéria (#10)
- [x] Tweetar edição do diário uma vez por dia (#15)

**Comment by anapaulagomes** [comment]
Sugestões de texto para o tweet:

* Saiu uma nova edição do #diáriooficial do executivo de #feiradesantana (10/08/2021 - Ano VII - Edição Nº 1817):
http://diariooficial.feiradesantana.ba.gov.br/atos/executivo/1XK91T09082021.pdf

**Comment by anapaulagomes** [comment]
Feito. Parabéns, @luandadantas! 🎉 👏🏽 
https://twitter.com/DiarioDeFeira/status/1435205497116930048?s=20
